version: '3'


services:
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust the port if needed
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  

      
      # Adjust the port if needed
#     networks:
#       - mern-app
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:3.6.19-xenial
#     ports:
#       - "27017:27017"
#     networks:
#       - mern-app
#     volumes:
#       - mongo-data:/data/db
# networks:
#   mern-app:
#     driver: bridge
# volumes:
#   mongo-data:
#     driver: local

# server:
#         build: ./backend
#         expose:
#             - 5600
#         ports:
#             - 5600:5600
#         volumes:
#             - ./backend/src:/srv/app/admin-server/src
#         depends_on:
#             - mongo    
#         command: npm run start

# client:
#         build: ./frontend
#         expose:
#             - 3000   
#         ports:
#             - 80:3000
#         volumes:
#             - ./frontend/src:/srv/app/admin-client/src
#             - ./frontend/public:/srv/app/admin-client/public
#         stdin_open: true
#         command: npm run start        

# mongo:
#         image: mongo
#         ports:
#             - "27017:27017"



# services:
#   frontend:
#     build:
#       context: ./Frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"  # Adjust the port if needed
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./Backend
#       dockerfile: Dockerfile
#     ports:
#       - "5600:5600"  # Adjust the port if needed
